CREATE DATABASE IF NOT EXISTS footballdb;
CREATE DATABASE IF NOT EXISTS footballdb_testing;

GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `footballdb`.* TO 'homestead'@'%';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `footballdb_testing`.* TO 'homestead'@'%';

FLUSH PRIVILEGES;