<?php

namespace Tests\Unit\Domain\Fixture\Policy;

use App\Domain\Fixture\Policy\ChancePolicy;
use Tests\TestCase;

class ChancePolicyTest extends TestCase
{
    private ChancePolicy $chancePolicy;
    protected function setUp(): void
    {
        $this->chancePolicy = app()->make(ChancePolicy::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetChance()
    {
        $result = $this->chancePolicy->getChance();
        $this->assertGreaterThanOrEqual(0, $result);
        $this->assertLessThanOrEqual(100, $result);
    }
}
