<?php

namespace Tests\Unit\Domain\Fixture\Policy;

use App\Domain\Fixture\Policy\ScoresPolicy;
use Tests\TestCase;

class ScoresPolicyTest extends TestCase
{
    private ScoresPolicy $scoresPolicy;
    protected function setUp(): void
    {
        $this->scoresPolicy = app()->make(ScoresPolicy::class);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetScoreDifference()
    {
        $result = $this->scoresPolicy->getScoreDifference(ScoresPolicy::GOAL_DIFFERENCE_COEFFICIENT);
        $this->assertEquals(1, $result);
        $result = $this->scoresPolicy->getScoreDifference(0);
        $this->assertEquals(0, $result);
    }
}
